// AssertError tests
//
// AssertError inherits its methods from Error.

function testInitializer_noFrames() {
    var err = AssertError("Failure");
    assertEQ(err.message(), "Failure");
    assertEmpty(err.traces());
}

function testInitializer_frames() {
    var err = AssertError("Failure", "A", "B");
    assertEQ(err.message(), "Failure");
    assertEQ(err.traces(), ["A", "B"]);
}

function testCanThrow() {
    var err = AssertError("Failure", "A", "B");
    assertError(\-> { throw err; },
        "Failure");
}

